### ISSUE TITLE
Question: How to implement multi-line comments? /* ... */

### ISSUE THREAD

**Issue by andreypfau** [alllex/parsus#29]

**Comment by alllex** [comment]
Hey! It depends on what you want to achieve

If you want to ignore them among other constructs you are parsing, then you can define the comments as a ignored token

```
object MyGrammar : Grammar<String>() {
    init {
        // multiline comment
        regexToken(Regex("/\\*.*?\\*/", RegexOption.MULTILINE), ignored = true)
    }
    
    override val root by literalToken("hello") map { it.text }
}
```

The `regexToken` is marked as `ignored`, which means that when it is encountered in the input and not expected, it is parsed (input is consumed), but the result is ignored. The token does not need to be assigned, only registered. That's why it can be just created in the `init` block.

**Comment by andreypfau** [comment]
Thank you, that works as i expected!
